MVC/projeto-gamer/Controllers/EquipeController.cs
using Microsoft.AspNetCore.Mvc;
using projeto_gamer.Infra;
using projeto_gamer.Models;

namespace projeto_gamer.Controllers
{
    [Route("[controller]")]
    public class EquipeController : Controller
    {
        private readonly ILogger<EquipeController> _logger;

        public EquipeController(ILogger<EquipeController> logger)
        {
            _logger = logger;
        }
        //Instância do objeto da classe Context
        Context c = new Context();

        //                               controller/action
        [Route("Listar")]//http://localhost/Equipe/Listar
        public IActionResult Index()
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");

            //"mochila" que contém a lista das equipes
            //Podemos usar essa mochila na View de equipe
            ViewBag.Equipe = c.Equipe.ToList();
            //Retorna a View da classe Equipe
            return View();
        }

        [Route("Cadastrar")]
        public IActionResult Cadastrar(IFormCollection form)
        {
            Equipe novaEquipe = new Equipe();

            novaEquipe.Nome = form["Nome"].ToString();

            //Vem como string
            // novaEquipe.Imagem = form["Imagem"].ToString();

            //Aqui começa a lógica do upload de imagem
            if (form.Files.Count > 0)
            {
                //Armazena o arquivo da imagem
                var file = form.Files[0];
                //Encontra a pasta do projeto
                var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Equipes");
                //Verifica se a pasta existe
                if (!Directory.Exists(folder))
                {
                    //Cria a pasta
                    Directory.CreateDirectory(folder);

                }
                //
                var path = Path.Combine(folder, file.FileName);
                //
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    //Copia para o caminho
                    file.CopyTo(stream);
                }
                //Atribui nome do arquivo da imagem
                novaEquipe.Imagem = file.FileName;
            }
            else
            {
                novaEquipe.Imagem = "padrao.png";
            }

            c.Equipe.Add(novaEquipe);
            //c.Add(novaEquipe);

            c.SaveChanges();

            return LocalRedirect("~/Equipe/Listar");
        }

        [Route("Excluir/{id}")]
        public IActionResult Excluir(int id)
        {
            try
            {
                Equipe equipeExcluida = c.Equipe.First(equipeBuscada => equipeBuscada.IdEquipe == id);

                c.Equipe.Remove(equipeExcluida);

                c.SaveChanges();

                return LocalRedirect("~/Equipe/Listar");
            }
            catch (System.Exception)
            {
                // TODO
                return LocalRedirect("~/Equipe/Erro");
            }
        }

        public IActionResult Editar(int id)
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");

            Equipe equipeBuscada = c.Equipe.First(equipeBuscada => equipeBuscada.IdEquipe == id);

            ViewBag.Equipe = equipeBuscada;

            return View("Edit");
        }

        [Route("Atualizar")]
        public IActionResult Atualizar(IFormCollection form, Equipe equipeBuscada)
        {
            Equipe novaEquipe = new Equipe();

            novaEquipe.Nome = equipeBuscada.Nome;

            //upload da imagem da equipe atualizada
            if (form.Files.Count > 0)
            {
                var file = form.Files[0];

                var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Equipes");

                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);

                }
                var path = Path.Combine(folder, file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                novaEquipe.Imagem = file.FileName;
            }
            else
            {
                novaEquipe.Imagem = "padrao.png";
            }



            Equipe equipe = c.Equipe.First(x => x.IdEquipe == equipeBuscada.IdEquipe);

            equipe.Nome = novaEquipe.Nome;
            equipe.Imagem = novaEquipe.Imagem;

            c.Equipe.Update(equipe);

            c.SaveChanges();

            return LocalRedirect("~/Equipe/Listar");
        }

        [Route("Erro")]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Erro");
        }
    }
}

MVC/projeto-gamer/Controllers/JogadorController.cs
using Microsoft.AspNetCore.Mvc;
using projeto_gamer.Infra;
using projeto_gamer.Models;

namespace projeto_gamer.Controllers
{
    [Route("[controller]")]
    public class JogadorController : Controller
    {
        private readonly ILogger<JogadorController> _logger;

        public JogadorController(ILogger<JogadorController> logger)
        {
            _logger = logger;
        }
        //Instância do objeto da classe Context
        Context c = new Context();

        //                               controller/action
        [Route("Listar")]//http://localhost/Jogador/Listar
        public IActionResult Index()
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");

            //"mochila" que contém a lista dos Jogadores
            //Podemos usar essa mochila na View de Jogador
            ViewBag.Jogador = c.Jogador.ToList();
            ViewBag.Equipe = c.Equipe.ToList();
            //Retorna a View da classe Jogador
            return View();
        }

        [Route("Cadastrar")]
        public IActionResult Cadastrar(IFormCollection form)
        {
            Jogador novoJogador = new Jogador();

            novoJogador.Nome = form["Nome"].ToString();
            novoJogador.Email = form["Email"].ToString();
            novoJogador.Senha = form["Senha"].ToString();
            novoJogador.IdEquipe = int.Parse(form["Equipe"].ToString());

            c.Jogador.Add(novoJogador);
            //c.Add(novoJogador);

            c.SaveChanges();

            return LocalRedirect("~/Jogador/Listar");
        }

        [Route("Excluir/{id}")]
        public IActionResult Excluir(int id)
        {
            try
            {
                Jogador e = c.Jogador.First(j => j.IdJogador == id);

                c.Jogador.Remove(e);

                c.SaveChanges();

                return LocalRedirect("~/Jogador/Listar");
            }
            catch (System.Exception)
            {
                // TODO
                return LocalRedirect("~/Jogador/Erro");
            }
        }
        public IActionResult Editar(int id)
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");

            Jogador jogadorBuscado = c.Jogador.First(jogadorBuscado => jogadorBuscado.IdJogador == id);

            ViewBag.Jogador = jogadorBuscado;
            ViewBag.Equipe = c.Equipe.ToList();

            return View("Edit");
        }

        [Route("Atualizar")]
        public IActionResult Atualizar(IFormCollection form)
        {
            Jogador novoJogador = new Jogador();

            novoJogador.IdJogador = int.Parse(form["IdJogador"].ToString());

            novoJogador.Nome = form["Nome"].ToString();
            novoJogador.Email = form["Email"].ToString();
            novoJogador.Senha = form["Senha"].ToString();
            novoJogador.IdEquipe = int.Parse(form["IdEquipe"].ToString());

            Jogador JogadorEditado = c.Jogador.First(x => x.IdJogador == novoJogador.IdJogador);

            JogadorEditado.Nome = novoJogador.Nome;
            JogadorEditado.Email = novoJogador.Email;
            JogadorEditado.Senha = novoJogador.Senha;
            JogadorEditado.IdEquipe = novoJogador.IdEquipe;

            c.Jogador.Update(JogadorEditado);

            c.SaveChanges();

            return LocalRedirect("~/Jogador/Listar");
        }

        [Route("Erro")]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Erro");
        }
    }
}

MVC/projeto-gamer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - projeto_gamer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/projeto_gamer.styles.css" asp-append-version="true" />
</head>
<body class="">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">projeto_gamer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Link para a página Home" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Link para a página Privacy" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@

                        @if (ViewBag.UserName != null)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Link para a página Index" asp-controller="Equipe" asp-action="Index">Equipes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Link para a página Index" asp-controller="Jogador" asp-action="Index">Jogadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Link para a página Index" asp-controller="Login" asp-action="Logout">Logout</a>
                        </li> 
                        <li class="nav-item nav-link text-dark">Olá @ViewBag.UserName, seja bem vindo!</li> 
                        }else{
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Link para a página Index" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                        }          
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - projeto_gamer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>